vich_uploader:
    db_driver: orm

    mappings:
       user_image:
           uri_prefix: assets/images/user
           upload_destination: '%kernel.project_dir%/public/assets/images/user'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
